version: "3"
services:
  kindle:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.kindle
    volumes:
        - ./:/kindle
  kindle-vertical:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.verticalKindle
    volumes:
        - ./:/kindle
